name = "clash-filter-api"
main = "src/index.js"
compatibility_date = "2023-05-18"

[observability.logs]
enabled = false

[vars]
DEFAULT_URL = "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml,https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml,https://raw.githubusercontent.com/qjlxg/aggregator/main/data/clash.yaml,https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml,https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml,https://raw.githubusercontent.com/Flikify/getNode/main/clash.yaml,https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml,https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml,https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml,https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/security/tls,https://zh.jikun.fun/share/col/%E6%B1%9F%E6%B1%9F%E5%85%AC%E7%9B%8A?token=1yGRuU-x6r_zEz28cE_pE,https://www.xrayvip.com/free.yaml,https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub,https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2,https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml,https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml,https://update.glados-config.com/mihomo/543454/7b9d17e/80064/glados.yaml"

[build]
command = "npm install"
